name: flutter_cine_time
description: Trailer app for theater

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  go_router: ^3.1.1
  provider: ^6.0.3
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/    
    - assets/icons/
    - assets/fonts/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"